services:
  - type: web
    name: oppstarter
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: AI_ENABLED
        value: true
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /_stcore/health
    autoDeploy: true
